version: '2'
services:
  elasticsearch:
    image: elasticsearch:2.4
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./e-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - magento2-network
networks:
  magento2-network:
