version: '3'
services:
  magento2-php:
    container_name: magento
    image: magento2-php74
    build: .
    ports:
      - "80:80"
      - "9001:9000"
    volumes:
      - .:/var/www/htdocs/html
    logging:
      driver: json-file
    networks:
      - magento2-network

  mariadb:
    image: mariadb:10.2
    ports:
      - "3300:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - magento2-network
    logging:
      driver: json-file

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=magento
      - PMA_PASSWORD=magento
      - MYSQL_ROOT_PASSWORD=magento
    depends_on:
      - mariadb
    ports:
      - "4000:4000"
    networks:
      - magento2-network
    logging:
      driver: json-file

  redis:
    image: redis
    ports:
      - "6379"
    networks:
      - magento2-network
    logging:
      driver: json-file

  redis-session:
    image: redis
    ports:
      - "6379"
    networks:
      - magento2-network
    logging:
      driver: json-file

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - magento2-network
    logging:
      driver: json-file

networks:
  magento2-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
